const MEMORIAL_CONFIRM = "確定? Are you sure?"
const MEMORIAL_UNEXPECTED_HAPPENED = "有問題發生 Something unexpected happened"
const MEMORIAL_SUCCESS = "成功 Success"
const MEMORIAL_PLEASE_ENTER = "請填入 Please input"
const MEMORIAL_PLEASE_SELECT = "請選擇 Please select"
const MEMORIAL_PLEASE_SELECT_OTHER = "請選擇其他 Please select other"
const MEMORIAL_AMOUNT_INVALID = "數額不對 Amount invalid"
const MEMORIAL_AT_LEAST_ONE = "至少 1. At least 1"
const MEMORIAL_AT_LEAST_ZERO = "至少 0. At least 0"
const MEMORIAL_ITEM = "項目 Item"
const MEMORIAL_ANCESTRALTABLET = "祖先牌位 AncestralTablet"
const MEMORIAL_ANCESTRALTABLET_X_MAX = 100
const MEMORIAL_ANCESTRALTABLET_Y_MAX = 100
const MEMORIAL_COLUMBARIUM_X_MAX = 100
const MEMORIAL_COLUMBARIUM_Y_MAX = 100