const MEMORIAL_CONFIRM = "確定? Are you sure?"
const MEMORIAL_UNEXPECTED_HAPPENED = "有問題發生 Something unexpected happened"
const MEMORIAL_SUCCESS = "成功 Success"
const MEMORIAL_PLEASE_ENTER = "請填入 Please input"
const MEMORIAL_AMOUNT_INVALID = "數額不對 Amount invalid"
const MEMORIAL_AT_LEAST_ONE = "至少 1. At least 1"
const MEMORIAL_AT_LEAST_ZERO = "至少 0. At least 0"