// <auto-generated />
namespace Memorial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RenameDeceasedToDeceased1ForQuadrangleTransaction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameDeceasedToDeceased1ForQuadrangleTransaction));
        
        string IMigrationMetadata.Id
        {
            get { return "202103161608117_RenameDeceasedToDeceased1ForQuadrangleTransaction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
