namespace Memorial.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AuditRenameDeleteDateToDeletedDate : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.AncestralTabletAreas", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.AncestralTabletItems", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.AncestralTabletTransactions", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.AncestralTablets", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Applicants", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.ApplicantDeceaseds", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Deceaseds", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.CemeteryTransactions", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.CemeteryItems", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Plots", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.CemeteryAreas", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Sites", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Catalogs", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumItems", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumCentres", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumAreas", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Niches", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumTransactions", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.FuneralCompanies", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.CremationItems", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Cremations", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Invoices", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.CemeteryLandscapeCompanies", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.MiscellaneousItems", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Miscellaneous", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Receipts", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.SpaceTransactions", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.SpaceItems", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Spaces", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.UrnTransactions", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.UrnItems", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Urns", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.NicheTypes", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.PlotTypes", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.FengShuiMasters", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.GenderTypes", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.MaritalTypes", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.NationalityTypes", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.ReligionTypes", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.RelationshipTypes", "DeletedDate", c => c.DateTime());
            DropColumn("dbo.AncestralTabletAreas", "DeleteDate");
            DropColumn("dbo.AncestralTabletItems", "DeleteDate");
            DropColumn("dbo.AncestralTabletTransactions", "DeleteDate");
            DropColumn("dbo.AncestralTablets", "DeleteDate");
            DropColumn("dbo.Applicants", "DeleteDate");
            DropColumn("dbo.ApplicantDeceaseds", "DeleteDate");
            DropColumn("dbo.Deceaseds", "DeleteDate");
            DropColumn("dbo.CemeteryTransactions", "DeleteDate");
            DropColumn("dbo.CemeteryItems", "DeleteDate");
            DropColumn("dbo.Plots", "DeleteDate");
            DropColumn("dbo.CemeteryAreas", "DeleteDate");
            DropColumn("dbo.Sites", "DeleteDate");
            DropColumn("dbo.Catalogs", "DeleteDate");
            DropColumn("dbo.ColumbariumItems", "DeleteDate");
            DropColumn("dbo.ColumbariumCentres", "DeleteDate");
            DropColumn("dbo.ColumbariumAreas", "DeleteDate");
            DropColumn("dbo.Niches", "DeleteDate");
            DropColumn("dbo.ColumbariumTransactions", "DeleteDate");
            DropColumn("dbo.FuneralCompanies", "DeleteDate");
            DropColumn("dbo.CremationItems", "DeleteDate");
            DropColumn("dbo.Cremations", "DeleteDate");
            DropColumn("dbo.Invoices", "DeleteDate");
            DropColumn("dbo.CemeteryLandscapeCompanies", "DeleteDate");
            DropColumn("dbo.MiscellaneousItems", "DeleteDate");
            DropColumn("dbo.Miscellaneous", "DeleteDate");
            DropColumn("dbo.Receipts", "DeleteDate");
            DropColumn("dbo.SpaceTransactions", "DeleteDate");
            DropColumn("dbo.SpaceItems", "DeleteDate");
            DropColumn("dbo.Spaces", "DeleteDate");
            DropColumn("dbo.UrnTransactions", "DeleteDate");
            DropColumn("dbo.UrnItems", "DeleteDate");
            DropColumn("dbo.Urns", "DeleteDate");
            DropColumn("dbo.NicheTypes", "DeleteDate");
            DropColumn("dbo.PlotTypes", "DeleteDate");
            DropColumn("dbo.FengShuiMasters", "DeleteDate");
            DropColumn("dbo.GenderTypes", "DeleteDate");
            DropColumn("dbo.MaritalTypes", "DeleteDate");
            DropColumn("dbo.NationalityTypes", "DeleteDate");
            DropColumn("dbo.ReligionTypes", "DeleteDate");
            DropColumn("dbo.RelationshipTypes", "DeleteDate");
        }
        
        public override void Down()
        {
            AddColumn("dbo.RelationshipTypes", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.ReligionTypes", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.NationalityTypes", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.MaritalTypes", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.GenderTypes", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.FengShuiMasters", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.PlotTypes", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.NicheTypes", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.Urns", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.UrnItems", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.UrnTransactions", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.Spaces", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.SpaceItems", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.SpaceTransactions", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.Receipts", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.Miscellaneous", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.MiscellaneousItems", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.CemeteryLandscapeCompanies", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.Invoices", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.Cremations", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.CremationItems", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.FuneralCompanies", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumTransactions", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.Niches", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumAreas", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumCentres", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumItems", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.Catalogs", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.Sites", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.CemeteryAreas", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.Plots", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.CemeteryItems", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.CemeteryTransactions", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.Deceaseds", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.ApplicantDeceaseds", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.Applicants", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.AncestralTablets", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.AncestralTabletTransactions", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.AncestralTabletItems", "DeleteDate", c => c.DateTime());
            AddColumn("dbo.AncestralTabletAreas", "DeleteDate", c => c.DateTime());
            DropColumn("dbo.RelationshipTypes", "DeletedDate");
            DropColumn("dbo.ReligionTypes", "DeletedDate");
            DropColumn("dbo.NationalityTypes", "DeletedDate");
            DropColumn("dbo.MaritalTypes", "DeletedDate");
            DropColumn("dbo.GenderTypes", "DeletedDate");
            DropColumn("dbo.FengShuiMasters", "DeletedDate");
            DropColumn("dbo.PlotTypes", "DeletedDate");
            DropColumn("dbo.NicheTypes", "DeletedDate");
            DropColumn("dbo.Urns", "DeletedDate");
            DropColumn("dbo.UrnItems", "DeletedDate");
            DropColumn("dbo.UrnTransactions", "DeletedDate");
            DropColumn("dbo.Spaces", "DeletedDate");
            DropColumn("dbo.SpaceItems", "DeletedDate");
            DropColumn("dbo.SpaceTransactions", "DeletedDate");
            DropColumn("dbo.Receipts", "DeletedDate");
            DropColumn("dbo.Miscellaneous", "DeletedDate");
            DropColumn("dbo.MiscellaneousItems", "DeletedDate");
            DropColumn("dbo.CemeteryLandscapeCompanies", "DeletedDate");
            DropColumn("dbo.Invoices", "DeletedDate");
            DropColumn("dbo.Cremations", "DeletedDate");
            DropColumn("dbo.CremationItems", "DeletedDate");
            DropColumn("dbo.FuneralCompanies", "DeletedDate");
            DropColumn("dbo.ColumbariumTransactions", "DeletedDate");
            DropColumn("dbo.Niches", "DeletedDate");
            DropColumn("dbo.ColumbariumAreas", "DeletedDate");
            DropColumn("dbo.ColumbariumCentres", "DeletedDate");
            DropColumn("dbo.ColumbariumItems", "DeletedDate");
            DropColumn("dbo.Catalogs", "DeletedDate");
            DropColumn("dbo.Sites", "DeletedDate");
            DropColumn("dbo.CemeteryAreas", "DeletedDate");
            DropColumn("dbo.Plots", "DeletedDate");
            DropColumn("dbo.CemeteryItems", "DeletedDate");
            DropColumn("dbo.CemeteryTransactions", "DeletedDate");
            DropColumn("dbo.Deceaseds", "DeletedDate");
            DropColumn("dbo.ApplicantDeceaseds", "DeletedDate");
            DropColumn("dbo.Applicants", "DeletedDate");
            DropColumn("dbo.AncestralTablets", "DeletedDate");
            DropColumn("dbo.AncestralTabletTransactions", "DeletedDate");
            DropColumn("dbo.AncestralTabletItems", "DeletedDate");
            DropColumn("dbo.AncestralTabletAreas", "DeletedDate");
        }
    }
}
