namespace Memorial.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AuditRenameCreateDateToCreatedDate : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.AncestralTabletAreas", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AncestralTabletItems", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AncestralTabletTransactions", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AncestralTablets", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Applicants", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ApplicantDeceaseds", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Deceaseds", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CemeteryTransactions", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CemeteryItems", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Plots", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CemeteryAreas", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Sites", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Catalogs", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ColumbariumItems", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ColumbariumCentres", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ColumbariumAreas", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Niches", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ColumbariumTransactions", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.FuneralCompanies", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CremationItems", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Cremations", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Invoices", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CemeteryLandscapeCompanies", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.MiscellaneousItems", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Miscellaneous", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Receipts", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.SpaceTransactions", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.SpaceItems", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Spaces", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.UrnTransactions", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.UrnItems", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Urns", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.NicheTypes", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.PlotTypes", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.FengShuiMasters", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.GenderTypes", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.MaritalTypes", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.NationalityTypes", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ReligionTypes", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.RelationshipTypes", "CreatedDate", c => c.DateTime(nullable: false));
            DropColumn("dbo.AncestralTabletAreas", "CreateDate");
            DropColumn("dbo.AncestralTabletItems", "CreateDate");
            DropColumn("dbo.AncestralTabletTransactions", "CreateDate");
            DropColumn("dbo.AncestralTablets", "CreateDate");
            DropColumn("dbo.Applicants", "CreateDate");
            DropColumn("dbo.ApplicantDeceaseds", "CreateDate");
            DropColumn("dbo.Deceaseds", "CreateDate");
            DropColumn("dbo.CemeteryTransactions", "CreateDate");
            DropColumn("dbo.CemeteryItems", "CreateDate");
            DropColumn("dbo.Plots", "CreateDate");
            DropColumn("dbo.CemeteryAreas", "CreateDate");
            DropColumn("dbo.Sites", "CreateDate");
            DropColumn("dbo.Catalogs", "CreateDate");
            DropColumn("dbo.ColumbariumItems", "CreateDate");
            DropColumn("dbo.ColumbariumCentres", "CreateDate");
            DropColumn("dbo.ColumbariumAreas", "CreateDate");
            DropColumn("dbo.Niches", "CreateDate");
            DropColumn("dbo.ColumbariumTransactions", "CreateDate");
            DropColumn("dbo.FuneralCompanies", "CreateDate");
            DropColumn("dbo.CremationItems", "CreateDate");
            DropColumn("dbo.Cremations", "CreateDate");
            DropColumn("dbo.Invoices", "CreateDate");
            DropColumn("dbo.CemeteryLandscapeCompanies", "CreateDate");
            DropColumn("dbo.MiscellaneousItems", "CreateDate");
            DropColumn("dbo.Miscellaneous", "CreateDate");
            DropColumn("dbo.Receipts", "CreateDate");
            DropColumn("dbo.SpaceTransactions", "CreateDate");
            DropColumn("dbo.SpaceItems", "CreateDate");
            DropColumn("dbo.Spaces", "CreateDate");
            DropColumn("dbo.UrnTransactions", "CreateDate");
            DropColumn("dbo.UrnItems", "CreateDate");
            DropColumn("dbo.Urns", "CreateDate");
            DropColumn("dbo.NicheTypes", "CreateDate");
            DropColumn("dbo.PlotTypes", "CreateDate");
            DropColumn("dbo.FengShuiMasters", "CreateDate");
            DropColumn("dbo.GenderTypes", "CreateDate");
            DropColumn("dbo.MaritalTypes", "CreateDate");
            DropColumn("dbo.NationalityTypes", "CreateDate");
            DropColumn("dbo.ReligionTypes", "CreateDate");
            DropColumn("dbo.RelationshipTypes", "CreateDate");
        }
        
        public override void Down()
        {
            AddColumn("dbo.RelationshipTypes", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ReligionTypes", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.NationalityTypes", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.MaritalTypes", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.GenderTypes", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.FengShuiMasters", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.PlotTypes", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.NicheTypes", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Urns", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.UrnItems", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.UrnTransactions", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Spaces", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.SpaceItems", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.SpaceTransactions", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Receipts", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Miscellaneous", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.MiscellaneousItems", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CemeteryLandscapeCompanies", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Invoices", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Cremations", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CremationItems", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.FuneralCompanies", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ColumbariumTransactions", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Niches", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ColumbariumAreas", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ColumbariumCentres", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ColumbariumItems", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Catalogs", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Sites", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CemeteryAreas", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Plots", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CemeteryItems", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CemeteryTransactions", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Deceaseds", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ApplicantDeceaseds", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Applicants", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AncestralTablets", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AncestralTabletTransactions", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AncestralTabletItems", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AncestralTabletAreas", "CreateDate", c => c.DateTime(nullable: false));
            DropColumn("dbo.RelationshipTypes", "CreatedDate");
            DropColumn("dbo.ReligionTypes", "CreatedDate");
            DropColumn("dbo.NationalityTypes", "CreatedDate");
            DropColumn("dbo.MaritalTypes", "CreatedDate");
            DropColumn("dbo.GenderTypes", "CreatedDate");
            DropColumn("dbo.FengShuiMasters", "CreatedDate");
            DropColumn("dbo.PlotTypes", "CreatedDate");
            DropColumn("dbo.NicheTypes", "CreatedDate");
            DropColumn("dbo.Urns", "CreatedDate");
            DropColumn("dbo.UrnItems", "CreatedDate");
            DropColumn("dbo.UrnTransactions", "CreatedDate");
            DropColumn("dbo.Spaces", "CreatedDate");
            DropColumn("dbo.SpaceItems", "CreatedDate");
            DropColumn("dbo.SpaceTransactions", "CreatedDate");
            DropColumn("dbo.Receipts", "CreatedDate");
            DropColumn("dbo.Miscellaneous", "CreatedDate");
            DropColumn("dbo.MiscellaneousItems", "CreatedDate");
            DropColumn("dbo.CemeteryLandscapeCompanies", "CreatedDate");
            DropColumn("dbo.Invoices", "CreatedDate");
            DropColumn("dbo.Cremations", "CreatedDate");
            DropColumn("dbo.CremationItems", "CreatedDate");
            DropColumn("dbo.FuneralCompanies", "CreatedDate");
            DropColumn("dbo.ColumbariumTransactions", "CreatedDate");
            DropColumn("dbo.Niches", "CreatedDate");
            DropColumn("dbo.ColumbariumAreas", "CreatedDate");
            DropColumn("dbo.ColumbariumCentres", "CreatedDate");
            DropColumn("dbo.ColumbariumItems", "CreatedDate");
            DropColumn("dbo.Catalogs", "CreatedDate");
            DropColumn("dbo.Sites", "CreatedDate");
            DropColumn("dbo.CemeteryAreas", "CreatedDate");
            DropColumn("dbo.Plots", "CreatedDate");
            DropColumn("dbo.CemeteryItems", "CreatedDate");
            DropColumn("dbo.CemeteryTransactions", "CreatedDate");
            DropColumn("dbo.Deceaseds", "CreatedDate");
            DropColumn("dbo.ApplicantDeceaseds", "CreatedDate");
            DropColumn("dbo.Applicants", "CreatedDate");
            DropColumn("dbo.AncestralTablets", "CreatedDate");
            DropColumn("dbo.AncestralTabletTransactions", "CreatedDate");
            DropColumn("dbo.AncestralTabletItems", "CreatedDate");
            DropColumn("dbo.AncestralTabletAreas", "CreatedDate");
        }
    }
}
