namespace Memorial.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AuditRenameModifyDateToModifiedDate : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.AncestralTabletAreas", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.AncestralTabletItems", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.AncestralTabletTransactions", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.AncestralTablets", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Applicants", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.ApplicantDeceaseds", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Deceaseds", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.CemeteryTransactions", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.CemeteryItems", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Plots", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.CemeteryAreas", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Sites", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Catalogs", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumItems", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumCentres", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumAreas", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Niches", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumTransactions", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.FuneralCompanies", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.CremationItems", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Cremations", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Invoices", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.CemeteryLandscapeCompanies", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.MiscellaneousItems", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Miscellaneous", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Receipts", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.SpaceTransactions", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.SpaceItems", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Spaces", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.UrnTransactions", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.UrnItems", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Urns", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.NicheTypes", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.PlotTypes", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.FengShuiMasters", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.GenderTypes", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.MaritalTypes", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.NationalityTypes", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.ReligionTypes", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.RelationshipTypes", "ModifiedDate", c => c.DateTime());
            DropColumn("dbo.AncestralTabletAreas", "ModifyDate");
            DropColumn("dbo.AncestralTabletItems", "ModifyDate");
            DropColumn("dbo.AncestralTabletTransactions", "ModifyDate");
            DropColumn("dbo.AncestralTablets", "ModifyDate");
            DropColumn("dbo.Applicants", "ModifyDate");
            DropColumn("dbo.ApplicantDeceaseds", "ModifyDate");
            DropColumn("dbo.Deceaseds", "ModifyDate");
            DropColumn("dbo.CemeteryTransactions", "ModifyDate");
            DropColumn("dbo.CemeteryItems", "ModifyDate");
            DropColumn("dbo.Plots", "ModifyDate");
            DropColumn("dbo.CemeteryAreas", "ModifyDate");
            DropColumn("dbo.Sites", "ModifyDate");
            DropColumn("dbo.Catalogs", "ModifyDate");
            DropColumn("dbo.ColumbariumItems", "ModifyDate");
            DropColumn("dbo.ColumbariumCentres", "ModifyDate");
            DropColumn("dbo.ColumbariumAreas", "ModifyDate");
            DropColumn("dbo.Niches", "ModifyDate");
            DropColumn("dbo.ColumbariumTransactions", "ModifyDate");
            DropColumn("dbo.FuneralCompanies", "ModifyDate");
            DropColumn("dbo.CremationItems", "ModifyDate");
            DropColumn("dbo.Cremations", "ModifyDate");
            DropColumn("dbo.Invoices", "ModifyDate");
            DropColumn("dbo.CemeteryLandscapeCompanies", "ModifyDate");
            DropColumn("dbo.MiscellaneousItems", "ModifyDate");
            DropColumn("dbo.Miscellaneous", "ModifyDate");
            DropColumn("dbo.Receipts", "ModifyDate");
            DropColumn("dbo.SpaceTransactions", "ModifyDate");
            DropColumn("dbo.SpaceItems", "ModifyDate");
            DropColumn("dbo.Spaces", "ModifyDate");
            DropColumn("dbo.UrnTransactions", "ModifyDate");
            DropColumn("dbo.UrnItems", "ModifyDate");
            DropColumn("dbo.Urns", "ModifyDate");
            DropColumn("dbo.NicheTypes", "ModifyDate");
            DropColumn("dbo.PlotTypes", "ModifyDate");
            DropColumn("dbo.FengShuiMasters", "ModifyDate");
            DropColumn("dbo.GenderTypes", "ModifyDate");
            DropColumn("dbo.MaritalTypes", "ModifyDate");
            DropColumn("dbo.NationalityTypes", "ModifyDate");
            DropColumn("dbo.ReligionTypes", "ModifyDate");
            DropColumn("dbo.RelationshipTypes", "ModifyDate");
        }
        
        public override void Down()
        {
            AddColumn("dbo.RelationshipTypes", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.ReligionTypes", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.NationalityTypes", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.MaritalTypes", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.GenderTypes", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.FengShuiMasters", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.PlotTypes", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.NicheTypes", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.Urns", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.UrnItems", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.UrnTransactions", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.Spaces", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.SpaceItems", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.SpaceTransactions", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.Receipts", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.Miscellaneous", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.MiscellaneousItems", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.CemeteryLandscapeCompanies", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.Invoices", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.Cremations", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.CremationItems", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.FuneralCompanies", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumTransactions", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.Niches", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumAreas", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumCentres", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumItems", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.Catalogs", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.Sites", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.CemeteryAreas", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.Plots", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.CemeteryItems", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.CemeteryTransactions", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.Deceaseds", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.ApplicantDeceaseds", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.Applicants", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.AncestralTablets", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.AncestralTabletTransactions", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.AncestralTabletItems", "ModifyDate", c => c.DateTime());
            AddColumn("dbo.AncestralTabletAreas", "ModifyDate", c => c.DateTime());
            DropColumn("dbo.RelationshipTypes", "ModifiedDate");
            DropColumn("dbo.ReligionTypes", "ModifiedDate");
            DropColumn("dbo.NationalityTypes", "ModifiedDate");
            DropColumn("dbo.MaritalTypes", "ModifiedDate");
            DropColumn("dbo.GenderTypes", "ModifiedDate");
            DropColumn("dbo.FengShuiMasters", "ModifiedDate");
            DropColumn("dbo.PlotTypes", "ModifiedDate");
            DropColumn("dbo.NicheTypes", "ModifiedDate");
            DropColumn("dbo.Urns", "ModifiedDate");
            DropColumn("dbo.UrnItems", "ModifiedDate");
            DropColumn("dbo.UrnTransactions", "ModifiedDate");
            DropColumn("dbo.Spaces", "ModifiedDate");
            DropColumn("dbo.SpaceItems", "ModifiedDate");
            DropColumn("dbo.SpaceTransactions", "ModifiedDate");
            DropColumn("dbo.Receipts", "ModifiedDate");
            DropColumn("dbo.Miscellaneous", "ModifiedDate");
            DropColumn("dbo.MiscellaneousItems", "ModifiedDate");
            DropColumn("dbo.CemeteryLandscapeCompanies", "ModifiedDate");
            DropColumn("dbo.Invoices", "ModifiedDate");
            DropColumn("dbo.Cremations", "ModifiedDate");
            DropColumn("dbo.CremationItems", "ModifiedDate");
            DropColumn("dbo.FuneralCompanies", "ModifiedDate");
            DropColumn("dbo.ColumbariumTransactions", "ModifiedDate");
            DropColumn("dbo.Niches", "ModifiedDate");
            DropColumn("dbo.ColumbariumAreas", "ModifiedDate");
            DropColumn("dbo.ColumbariumCentres", "ModifiedDate");
            DropColumn("dbo.ColumbariumItems", "ModifiedDate");
            DropColumn("dbo.Catalogs", "ModifiedDate");
            DropColumn("dbo.Sites", "ModifiedDate");
            DropColumn("dbo.CemeteryAreas", "ModifiedDate");
            DropColumn("dbo.Plots", "ModifiedDate");
            DropColumn("dbo.CemeteryItems", "ModifiedDate");
            DropColumn("dbo.CemeteryTransactions", "ModifiedDate");
            DropColumn("dbo.Deceaseds", "ModifiedDate");
            DropColumn("dbo.ApplicantDeceaseds", "ModifiedDate");
            DropColumn("dbo.Applicants", "ModifiedDate");
            DropColumn("dbo.AncestralTablets", "ModifiedDate");
            DropColumn("dbo.AncestralTabletTransactions", "ModifiedDate");
            DropColumn("dbo.AncestralTabletItems", "ModifiedDate");
            DropColumn("dbo.AncestralTabletAreas", "ModifiedDate");
        }
    }
}
