namespace Memorial.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class RenameAuditDateColumns : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.AccessControls", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.AccessControls", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.AccessControls", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.AncestralTabletAreas", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.AncestralTabletAreas", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.AncestralTabletAreas", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.AncestralTabletItems", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.AncestralTabletItems", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.AncestralTabletItems", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.AncestralTabletTransactions", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.AncestralTabletTransactions", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.AncestralTabletTransactions", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.AncestralTablets", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.AncestralTablets", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.AncestralTablets", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.Applicants", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Applicants", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.Applicants", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.ApplicantDeceaseds", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.ApplicantDeceaseds", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.ApplicantDeceaseds", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.Deceaseds", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Deceaseds", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.Deceaseds", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.CemeteryTransactions", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.CemeteryTransactions", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.CemeteryTransactions", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.CemeteryItems", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.CemeteryItems", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.CemeteryItems", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.Plots", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Plots", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.Plots", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.CemeteryAreas", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.CemeteryAreas", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.CemeteryAreas", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.Sites", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Sites", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.Sites", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.Catalogs", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Catalogs", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.Catalogs", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.ColumbariumItems", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.ColumbariumItems", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.ColumbariumItems", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.ColumbariumCentres", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.ColumbariumCentres", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.ColumbariumCentres", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.ColumbariumAreas", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.ColumbariumAreas", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.ColumbariumAreas", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.Niches", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Niches", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.Niches", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.ColumbariumTransactions", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.ColumbariumTransactions", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.ColumbariumTransactions", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.FuneralCompanies", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.FuneralCompanies", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.FuneralCompanies", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.CremationTransactions", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.CremationTransactions", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.CremationTransactions", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.CremationItems", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.CremationItems", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.CremationItems", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.Cremations", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Cremations", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.Cremations", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.Invoices", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Invoices", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.Invoices", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.MiscellaneousTransactions", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.MiscellaneousTransactions", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.MiscellaneousTransactions", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.CemeteryLandscapeCompanies", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.CemeteryLandscapeCompanies", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.CemeteryLandscapeCompanies", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.MiscellaneousItems", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.MiscellaneousItems", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.MiscellaneousItems", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.Miscellaneous", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Miscellaneous", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.Miscellaneous", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.Receipts", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Receipts", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.Receipts", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.SpaceTransactions", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.SpaceTransactions", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.SpaceTransactions", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.SpaceItems", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.SpaceItems", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.SpaceItems", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.Spaces", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Spaces", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.Spaces", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.UrnTransactions", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.UrnTransactions", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.UrnTransactions", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.UrnItems", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.UrnItems", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.UrnItems", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.Urns", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Urns", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.Urns", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.NicheTypes", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.NicheTypes", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.NicheTypes", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.PlotTypes", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.PlotTypes", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.PlotTypes", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.FengShuiMasters", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.FengShuiMasters", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.FengShuiMasters", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.GenderTypes", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.GenderTypes", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.GenderTypes", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.MaritalTypes", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.MaritalTypes", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.MaritalTypes", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.NationalityTypes", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.NationalityTypes", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.NationalityTypes", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.ReligionTypes", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.ReligionTypes", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.ReligionTypes", "DeletedUtcTime", c => c.DateTime());
            AddColumn("dbo.RelationshipTypes", "CreatedUtcTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.RelationshipTypes", "ModifiedUtcTime", c => c.DateTime());
            AddColumn("dbo.RelationshipTypes", "DeletedUtcTime", c => c.DateTime());
            DropColumn("dbo.AccessControls", "CreatedDate");
            DropColumn("dbo.AccessControls", "ModifiedDate");
            DropColumn("dbo.AccessControls", "DeletedDate");
            DropColumn("dbo.AncestralTabletAreas", "CreatedDate");
            DropColumn("dbo.AncestralTabletAreas", "ModifiedDate");
            DropColumn("dbo.AncestralTabletAreas", "DeletedDate");
            DropColumn("dbo.AncestralTabletItems", "CreatedDate");
            DropColumn("dbo.AncestralTabletItems", "ModifiedDate");
            DropColumn("dbo.AncestralTabletItems", "DeletedDate");
            DropColumn("dbo.AncestralTabletTransactions", "CreatedDate");
            DropColumn("dbo.AncestralTabletTransactions", "ModifiedDate");
            DropColumn("dbo.AncestralTabletTransactions", "DeletedDate");
            DropColumn("dbo.AncestralTablets", "CreatedDate");
            DropColumn("dbo.AncestralTablets", "ModifiedDate");
            DropColumn("dbo.AncestralTablets", "DeletedDate");
            DropColumn("dbo.Applicants", "CreatedDate");
            DropColumn("dbo.Applicants", "ModifiedDate");
            DropColumn("dbo.Applicants", "DeletedDate");
            DropColumn("dbo.ApplicantDeceaseds", "CreatedDate");
            DropColumn("dbo.ApplicantDeceaseds", "ModifiedDate");
            DropColumn("dbo.ApplicantDeceaseds", "DeletedDate");
            DropColumn("dbo.Deceaseds", "CreatedDate");
            DropColumn("dbo.Deceaseds", "ModifiedDate");
            DropColumn("dbo.Deceaseds", "DeletedDate");
            DropColumn("dbo.CemeteryTransactions", "CreatedDate");
            DropColumn("dbo.CemeteryTransactions", "ModifiedDate");
            DropColumn("dbo.CemeteryTransactions", "DeletedDate");
            DropColumn("dbo.CemeteryItems", "CreatedDate");
            DropColumn("dbo.CemeteryItems", "ModifiedDate");
            DropColumn("dbo.CemeteryItems", "DeletedDate");
            DropColumn("dbo.Plots", "CreatedDate");
            DropColumn("dbo.Plots", "ModifiedDate");
            DropColumn("dbo.Plots", "DeletedDate");
            DropColumn("dbo.CemeteryAreas", "CreatedDate");
            DropColumn("dbo.CemeteryAreas", "ModifiedDate");
            DropColumn("dbo.CemeteryAreas", "DeletedDate");
            DropColumn("dbo.Sites", "CreatedDate");
            DropColumn("dbo.Sites", "ModifiedDate");
            DropColumn("dbo.Sites", "DeletedDate");
            DropColumn("dbo.Catalogs", "CreatedDate");
            DropColumn("dbo.Catalogs", "ModifiedDate");
            DropColumn("dbo.Catalogs", "DeletedDate");
            DropColumn("dbo.ColumbariumItems", "CreatedDate");
            DropColumn("dbo.ColumbariumItems", "ModifiedDate");
            DropColumn("dbo.ColumbariumItems", "DeletedDate");
            DropColumn("dbo.ColumbariumCentres", "CreatedDate");
            DropColumn("dbo.ColumbariumCentres", "ModifiedDate");
            DropColumn("dbo.ColumbariumCentres", "DeletedDate");
            DropColumn("dbo.ColumbariumAreas", "CreatedDate");
            DropColumn("dbo.ColumbariumAreas", "ModifiedDate");
            DropColumn("dbo.ColumbariumAreas", "DeletedDate");
            DropColumn("dbo.Niches", "CreatedDate");
            DropColumn("dbo.Niches", "ModifiedDate");
            DropColumn("dbo.Niches", "DeletedDate");
            DropColumn("dbo.ColumbariumTransactions", "CreatedDate");
            DropColumn("dbo.ColumbariumTransactions", "ModifiedDate");
            DropColumn("dbo.ColumbariumTransactions", "DeletedDate");
            DropColumn("dbo.FuneralCompanies", "CreatedDate");
            DropColumn("dbo.FuneralCompanies", "ModifiedDate");
            DropColumn("dbo.FuneralCompanies", "DeletedDate");
            DropColumn("dbo.CremationTransactions", "CreatedDate");
            DropColumn("dbo.CremationTransactions", "ModifiedDate");
            DropColumn("dbo.CremationTransactions", "DeletedDate");
            DropColumn("dbo.CremationItems", "CreatedDate");
            DropColumn("dbo.CremationItems", "ModifiedDate");
            DropColumn("dbo.CremationItems", "DeletedDate");
            DropColumn("dbo.Cremations", "CreatedDate");
            DropColumn("dbo.Cremations", "ModifiedDate");
            DropColumn("dbo.Cremations", "DeletedDate");
            DropColumn("dbo.Invoices", "CreatedDate");
            DropColumn("dbo.Invoices", "ModifiedDate");
            DropColumn("dbo.Invoices", "DeletedDate");
            DropColumn("dbo.MiscellaneousTransactions", "CreatedDate");
            DropColumn("dbo.MiscellaneousTransactions", "ModifiedDate");
            DropColumn("dbo.MiscellaneousTransactions", "DeletedDate");
            DropColumn("dbo.CemeteryLandscapeCompanies", "CreatedDate");
            DropColumn("dbo.CemeteryLandscapeCompanies", "ModifiedDate");
            DropColumn("dbo.CemeteryLandscapeCompanies", "DeletedDate");
            DropColumn("dbo.MiscellaneousItems", "CreatedDate");
            DropColumn("dbo.MiscellaneousItems", "ModifiedDate");
            DropColumn("dbo.MiscellaneousItems", "DeletedDate");
            DropColumn("dbo.Miscellaneous", "CreatedDate");
            DropColumn("dbo.Miscellaneous", "ModifiedDate");
            DropColumn("dbo.Miscellaneous", "DeletedDate");
            DropColumn("dbo.Receipts", "CreatedDate");
            DropColumn("dbo.Receipts", "ModifiedDate");
            DropColumn("dbo.Receipts", "DeletedDate");
            DropColumn("dbo.SpaceTransactions", "CreatedDate");
            DropColumn("dbo.SpaceTransactions", "ModifiedDate");
            DropColumn("dbo.SpaceTransactions", "DeletedDate");
            DropColumn("dbo.SpaceItems", "CreatedDate");
            DropColumn("dbo.SpaceItems", "ModifiedDate");
            DropColumn("dbo.SpaceItems", "DeletedDate");
            DropColumn("dbo.Spaces", "CreatedDate");
            DropColumn("dbo.Spaces", "ModifiedDate");
            DropColumn("dbo.Spaces", "DeletedDate");
            DropColumn("dbo.UrnTransactions", "CreatedDate");
            DropColumn("dbo.UrnTransactions", "ModifiedDate");
            DropColumn("dbo.UrnTransactions", "DeletedDate");
            DropColumn("dbo.UrnItems", "CreatedDate");
            DropColumn("dbo.UrnItems", "ModifiedDate");
            DropColumn("dbo.UrnItems", "DeletedDate");
            DropColumn("dbo.Urns", "CreatedDate");
            DropColumn("dbo.Urns", "ModifiedDate");
            DropColumn("dbo.Urns", "DeletedDate");
            DropColumn("dbo.NicheTypes", "CreatedDate");
            DropColumn("dbo.NicheTypes", "ModifiedDate");
            DropColumn("dbo.NicheTypes", "DeletedDate");
            DropColumn("dbo.PlotTypes", "CreatedDate");
            DropColumn("dbo.PlotTypes", "ModifiedDate");
            DropColumn("dbo.PlotTypes", "DeletedDate");
            DropColumn("dbo.FengShuiMasters", "CreatedDate");
            DropColumn("dbo.FengShuiMasters", "ModifiedDate");
            DropColumn("dbo.FengShuiMasters", "DeletedDate");
            DropColumn("dbo.GenderTypes", "CreatedDate");
            DropColumn("dbo.GenderTypes", "ModifiedDate");
            DropColumn("dbo.GenderTypes", "DeletedDate");
            DropColumn("dbo.MaritalTypes", "CreatedDate");
            DropColumn("dbo.MaritalTypes", "ModifiedDate");
            DropColumn("dbo.MaritalTypes", "DeletedDate");
            DropColumn("dbo.NationalityTypes", "CreatedDate");
            DropColumn("dbo.NationalityTypes", "ModifiedDate");
            DropColumn("dbo.NationalityTypes", "DeletedDate");
            DropColumn("dbo.ReligionTypes", "CreatedDate");
            DropColumn("dbo.ReligionTypes", "ModifiedDate");
            DropColumn("dbo.ReligionTypes", "DeletedDate");
            DropColumn("dbo.RelationshipTypes", "CreatedDate");
            DropColumn("dbo.RelationshipTypes", "ModifiedDate");
            DropColumn("dbo.RelationshipTypes", "DeletedDate");
        }
        
        public override void Down()
        {
            AddColumn("dbo.RelationshipTypes", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.RelationshipTypes", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.RelationshipTypes", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ReligionTypes", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.ReligionTypes", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.ReligionTypes", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.NationalityTypes", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.NationalityTypes", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.NationalityTypes", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.MaritalTypes", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.MaritalTypes", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.MaritalTypes", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.GenderTypes", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.GenderTypes", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.GenderTypes", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.FengShuiMasters", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.FengShuiMasters", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.FengShuiMasters", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.PlotTypes", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.PlotTypes", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.PlotTypes", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.NicheTypes", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.NicheTypes", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.NicheTypes", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Urns", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Urns", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Urns", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.UrnItems", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.UrnItems", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.UrnItems", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.UrnTransactions", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.UrnTransactions", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.UrnTransactions", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Spaces", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Spaces", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Spaces", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.SpaceItems", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.SpaceItems", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.SpaceItems", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.SpaceTransactions", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.SpaceTransactions", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.SpaceTransactions", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Receipts", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Receipts", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Receipts", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Miscellaneous", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Miscellaneous", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Miscellaneous", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.MiscellaneousItems", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.MiscellaneousItems", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.MiscellaneousItems", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CemeteryLandscapeCompanies", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.CemeteryLandscapeCompanies", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.CemeteryLandscapeCompanies", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.MiscellaneousTransactions", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.MiscellaneousTransactions", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.MiscellaneousTransactions", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Invoices", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Invoices", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Invoices", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Cremations", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Cremations", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Cremations", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CremationItems", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.CremationItems", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.CremationItems", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CremationTransactions", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.CremationTransactions", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.CremationTransactions", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.FuneralCompanies", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.FuneralCompanies", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.FuneralCompanies", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ColumbariumTransactions", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumTransactions", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumTransactions", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Niches", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Niches", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Niches", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ColumbariumAreas", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumAreas", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumAreas", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ColumbariumCentres", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumCentres", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumCentres", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ColumbariumItems", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumItems", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.ColumbariumItems", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Catalogs", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Catalogs", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Catalogs", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Sites", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Sites", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Sites", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CemeteryAreas", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.CemeteryAreas", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.CemeteryAreas", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Plots", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Plots", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Plots", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CemeteryItems", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.CemeteryItems", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.CemeteryItems", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CemeteryTransactions", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.CemeteryTransactions", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.CemeteryTransactions", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Deceaseds", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Deceaseds", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Deceaseds", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.ApplicantDeceaseds", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.ApplicantDeceaseds", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.ApplicantDeceaseds", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Applicants", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.Applicants", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Applicants", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AncestralTablets", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.AncestralTablets", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.AncestralTablets", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AncestralTabletTransactions", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.AncestralTabletTransactions", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.AncestralTabletTransactions", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AncestralTabletItems", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.AncestralTabletItems", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.AncestralTabletItems", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AncestralTabletAreas", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.AncestralTabletAreas", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.AncestralTabletAreas", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AccessControls", "DeletedDate", c => c.DateTime());
            AddColumn("dbo.AccessControls", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.AccessControls", "CreatedDate", c => c.DateTime(nullable: false));
            DropColumn("dbo.RelationshipTypes", "DeletedUtcTime");
            DropColumn("dbo.RelationshipTypes", "ModifiedUtcTime");
            DropColumn("dbo.RelationshipTypes", "CreatedUtcTime");
            DropColumn("dbo.ReligionTypes", "DeletedUtcTime");
            DropColumn("dbo.ReligionTypes", "ModifiedUtcTime");
            DropColumn("dbo.ReligionTypes", "CreatedUtcTime");
            DropColumn("dbo.NationalityTypes", "DeletedUtcTime");
            DropColumn("dbo.NationalityTypes", "ModifiedUtcTime");
            DropColumn("dbo.NationalityTypes", "CreatedUtcTime");
            DropColumn("dbo.MaritalTypes", "DeletedUtcTime");
            DropColumn("dbo.MaritalTypes", "ModifiedUtcTime");
            DropColumn("dbo.MaritalTypes", "CreatedUtcTime");
            DropColumn("dbo.GenderTypes", "DeletedUtcTime");
            DropColumn("dbo.GenderTypes", "ModifiedUtcTime");
            DropColumn("dbo.GenderTypes", "CreatedUtcTime");
            DropColumn("dbo.FengShuiMasters", "DeletedUtcTime");
            DropColumn("dbo.FengShuiMasters", "ModifiedUtcTime");
            DropColumn("dbo.FengShuiMasters", "CreatedUtcTime");
            DropColumn("dbo.PlotTypes", "DeletedUtcTime");
            DropColumn("dbo.PlotTypes", "ModifiedUtcTime");
            DropColumn("dbo.PlotTypes", "CreatedUtcTime");
            DropColumn("dbo.NicheTypes", "DeletedUtcTime");
            DropColumn("dbo.NicheTypes", "ModifiedUtcTime");
            DropColumn("dbo.NicheTypes", "CreatedUtcTime");
            DropColumn("dbo.Urns", "DeletedUtcTime");
            DropColumn("dbo.Urns", "ModifiedUtcTime");
            DropColumn("dbo.Urns", "CreatedUtcTime");
            DropColumn("dbo.UrnItems", "DeletedUtcTime");
            DropColumn("dbo.UrnItems", "ModifiedUtcTime");
            DropColumn("dbo.UrnItems", "CreatedUtcTime");
            DropColumn("dbo.UrnTransactions", "DeletedUtcTime");
            DropColumn("dbo.UrnTransactions", "ModifiedUtcTime");
            DropColumn("dbo.UrnTransactions", "CreatedUtcTime");
            DropColumn("dbo.Spaces", "DeletedUtcTime");
            DropColumn("dbo.Spaces", "ModifiedUtcTime");
            DropColumn("dbo.Spaces", "CreatedUtcTime");
            DropColumn("dbo.SpaceItems", "DeletedUtcTime");
            DropColumn("dbo.SpaceItems", "ModifiedUtcTime");
            DropColumn("dbo.SpaceItems", "CreatedUtcTime");
            DropColumn("dbo.SpaceTransactions", "DeletedUtcTime");
            DropColumn("dbo.SpaceTransactions", "ModifiedUtcTime");
            DropColumn("dbo.SpaceTransactions", "CreatedUtcTime");
            DropColumn("dbo.Receipts", "DeletedUtcTime");
            DropColumn("dbo.Receipts", "ModifiedUtcTime");
            DropColumn("dbo.Receipts", "CreatedUtcTime");
            DropColumn("dbo.Miscellaneous", "DeletedUtcTime");
            DropColumn("dbo.Miscellaneous", "ModifiedUtcTime");
            DropColumn("dbo.Miscellaneous", "CreatedUtcTime");
            DropColumn("dbo.MiscellaneousItems", "DeletedUtcTime");
            DropColumn("dbo.MiscellaneousItems", "ModifiedUtcTime");
            DropColumn("dbo.MiscellaneousItems", "CreatedUtcTime");
            DropColumn("dbo.CemeteryLandscapeCompanies", "DeletedUtcTime");
            DropColumn("dbo.CemeteryLandscapeCompanies", "ModifiedUtcTime");
            DropColumn("dbo.CemeteryLandscapeCompanies", "CreatedUtcTime");
            DropColumn("dbo.MiscellaneousTransactions", "DeletedUtcTime");
            DropColumn("dbo.MiscellaneousTransactions", "ModifiedUtcTime");
            DropColumn("dbo.MiscellaneousTransactions", "CreatedUtcTime");
            DropColumn("dbo.Invoices", "DeletedUtcTime");
            DropColumn("dbo.Invoices", "ModifiedUtcTime");
            DropColumn("dbo.Invoices", "CreatedUtcTime");
            DropColumn("dbo.Cremations", "DeletedUtcTime");
            DropColumn("dbo.Cremations", "ModifiedUtcTime");
            DropColumn("dbo.Cremations", "CreatedUtcTime");
            DropColumn("dbo.CremationItems", "DeletedUtcTime");
            DropColumn("dbo.CremationItems", "ModifiedUtcTime");
            DropColumn("dbo.CremationItems", "CreatedUtcTime");
            DropColumn("dbo.CremationTransactions", "DeletedUtcTime");
            DropColumn("dbo.CremationTransactions", "ModifiedUtcTime");
            DropColumn("dbo.CremationTransactions", "CreatedUtcTime");
            DropColumn("dbo.FuneralCompanies", "DeletedUtcTime");
            DropColumn("dbo.FuneralCompanies", "ModifiedUtcTime");
            DropColumn("dbo.FuneralCompanies", "CreatedUtcTime");
            DropColumn("dbo.ColumbariumTransactions", "DeletedUtcTime");
            DropColumn("dbo.ColumbariumTransactions", "ModifiedUtcTime");
            DropColumn("dbo.ColumbariumTransactions", "CreatedUtcTime");
            DropColumn("dbo.Niches", "DeletedUtcTime");
            DropColumn("dbo.Niches", "ModifiedUtcTime");
            DropColumn("dbo.Niches", "CreatedUtcTime");
            DropColumn("dbo.ColumbariumAreas", "DeletedUtcTime");
            DropColumn("dbo.ColumbariumAreas", "ModifiedUtcTime");
            DropColumn("dbo.ColumbariumAreas", "CreatedUtcTime");
            DropColumn("dbo.ColumbariumCentres", "DeletedUtcTime");
            DropColumn("dbo.ColumbariumCentres", "ModifiedUtcTime");
            DropColumn("dbo.ColumbariumCentres", "CreatedUtcTime");
            DropColumn("dbo.ColumbariumItems", "DeletedUtcTime");
            DropColumn("dbo.ColumbariumItems", "ModifiedUtcTime");
            DropColumn("dbo.ColumbariumItems", "CreatedUtcTime");
            DropColumn("dbo.Catalogs", "DeletedUtcTime");
            DropColumn("dbo.Catalogs", "ModifiedUtcTime");
            DropColumn("dbo.Catalogs", "CreatedUtcTime");
            DropColumn("dbo.Sites", "DeletedUtcTime");
            DropColumn("dbo.Sites", "ModifiedUtcTime");
            DropColumn("dbo.Sites", "CreatedUtcTime");
            DropColumn("dbo.CemeteryAreas", "DeletedUtcTime");
            DropColumn("dbo.CemeteryAreas", "ModifiedUtcTime");
            DropColumn("dbo.CemeteryAreas", "CreatedUtcTime");
            DropColumn("dbo.Plots", "DeletedUtcTime");
            DropColumn("dbo.Plots", "ModifiedUtcTime");
            DropColumn("dbo.Plots", "CreatedUtcTime");
            DropColumn("dbo.CemeteryItems", "DeletedUtcTime");
            DropColumn("dbo.CemeteryItems", "ModifiedUtcTime");
            DropColumn("dbo.CemeteryItems", "CreatedUtcTime");
            DropColumn("dbo.CemeteryTransactions", "DeletedUtcTime");
            DropColumn("dbo.CemeteryTransactions", "ModifiedUtcTime");
            DropColumn("dbo.CemeteryTransactions", "CreatedUtcTime");
            DropColumn("dbo.Deceaseds", "DeletedUtcTime");
            DropColumn("dbo.Deceaseds", "ModifiedUtcTime");
            DropColumn("dbo.Deceaseds", "CreatedUtcTime");
            DropColumn("dbo.ApplicantDeceaseds", "DeletedUtcTime");
            DropColumn("dbo.ApplicantDeceaseds", "ModifiedUtcTime");
            DropColumn("dbo.ApplicantDeceaseds", "CreatedUtcTime");
            DropColumn("dbo.Applicants", "DeletedUtcTime");
            DropColumn("dbo.Applicants", "ModifiedUtcTime");
            DropColumn("dbo.Applicants", "CreatedUtcTime");
            DropColumn("dbo.AncestralTablets", "DeletedUtcTime");
            DropColumn("dbo.AncestralTablets", "ModifiedUtcTime");
            DropColumn("dbo.AncestralTablets", "CreatedUtcTime");
            DropColumn("dbo.AncestralTabletTransactions", "DeletedUtcTime");
            DropColumn("dbo.AncestralTabletTransactions", "ModifiedUtcTime");
            DropColumn("dbo.AncestralTabletTransactions", "CreatedUtcTime");
            DropColumn("dbo.AncestralTabletItems", "DeletedUtcTime");
            DropColumn("dbo.AncestralTabletItems", "ModifiedUtcTime");
            DropColumn("dbo.AncestralTabletItems", "CreatedUtcTime");
            DropColumn("dbo.AncestralTabletAreas", "DeletedUtcTime");
            DropColumn("dbo.AncestralTabletAreas", "ModifiedUtcTime");
            DropColumn("dbo.AncestralTabletAreas", "CreatedUtcTime");
            DropColumn("dbo.AccessControls", "DeletedUtcTime");
            DropColumn("dbo.AccessControls", "ModifiedUtcTime");
            DropColumn("dbo.AccessControls", "CreatedUtcTime");
        }
    }
}
