//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mix {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mix() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Memorial.Mix", typeof(Mix).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住址&lt;br /&gt;Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年齡&lt;br /&gt;Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ancestor {
            get {
                return ResourceManager.GetString("Ancestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申請者 Applicant.
        /// </summary>
        public static string Applicant {
            get {
                return ResourceManager.GetString("Applicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全申請者 Applicants.
        /// </summary>
        public static string Applicants {
            get {
                return ResourceManager.GetString("Applicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 葬紙准證號碼&lt;br /&gt;Burial Certificate.
        /// </summary>
        public static string BurialCertificate {
            get {
                return ResourceManager.GetString("BurialCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （中）&lt;br /&gt;Chinese Name.
        /// </summary>
        public static string ChineseName {
            get {
                return ResourceManager.GetString("ChineseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Columbarium {
            get {
                return ResourceManager.GetString("Columbarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火化 Cremation.
        /// </summary>
        public static string Cremation {
            get {
                return ResourceManager.GetString("Cremation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生死局號碼&lt;br /&gt;Death Certificate.
        /// </summary>
        public static string DeathCertificate {
            get {
                return ResourceManager.GetString("DeathCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 逝世日期&lt;br /&gt;Death Date.
        /// </summary>
        public static string DeathDate {
            get {
                return ResourceManager.GetString("DeathDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 逝世登記處&lt;br /&gt;Death Registration Centre.
        /// </summary>
        public static string DeathRegistrationCentre {
            get {
                return ResourceManager.GetString("DeathRegistrationCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 逝世者 Deceased.
        /// </summary>
        public static string Deceased {
            get {
                return ResourceManager.GetString("Deceased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全逝世者 Deceaseds.
        /// </summary>
        public static string Deceaseds {
            get {
                return ResourceManager.GetString("Deceaseds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除 Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改 Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名（英）&lt;br /&gt;English Name.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性別&lt;br /&gt;Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住家電話&lt;br /&gt;House Phone.
        /// </summary>
        public static string HousePhone {
            get {
                return ResourceManager.GetString("HousePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身份證&lt;br/&gt;NRIC No.
        /// </summary>
        public static string IC {
            get {
                return ResourceManager.GetString("IC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 政府入口準字號數（如由外運棺來檳）&lt;br /&gt;Import Permit Number.
        /// </summary>
        public static string ImportPermitNumber {
            get {
                return ResourceManager.GetString("ImportPermitNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系 Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 婚姻&lt;br /&gt;Marital.
        /// </summary>
        public static string Marital {
            get {
                return ResourceManager.GetString("Marital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 杂费 Miscellaneous.
        /// </summary>
        public static string Miscellaneous {
            get {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流動電話&lt;br /&gt;Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 國籍&lt;br /&gt;Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新纪录 New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 沒記錄 No record.
        /// </summary>
        public static string NoRecord {
            get {
                return ResourceManager.GetString("NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Plot {
            get {
                return ResourceManager.GetString("Plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 骨灰阁 Quadrangle.
        /// </summary>
        public static string Quadrangle {
            get {
                return ResourceManager.GetString("Quadrangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申请人与逝世者关系&lt;br /&gt;Relationship.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信仰&lt;br /&gt;Religion.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 備註&lt;br /&gt;Remark.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存 Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空间 Space.
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除联系 Unlink.
        /// </summary>
        public static string Unlink {
            get {
                return ResourceManager.GetString("Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 骨灰瓮 Urn.
        /// </summary>
        public static string Urn {
            get {
                return ResourceManager.GetString("Urn", resourceCulture);
            }
        }
    }
}
