//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mix {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mix() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Memorial.Mix", typeof(Mix).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住址 Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住址&lt;br /&gt;Address.
        /// </summary>
        public static string AddressBR {
            get {
                return ResourceManager.GetString("AddressBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表格 AF.
        /// </summary>
        public static string AF {
            get {
                return ResourceManager.GetString("AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表格&lt;br /&gt;AF.
        /// </summary>
        public static string AFBR {
            get {
                return ResourceManager.GetString("AFBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年齡 Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年齡&lt;br /&gt;Age.
        /// </summary>
        public static string AgeBR {
            get {
                return ResourceManager.GetString("AgeBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We, the above-named signatories hereby declared and confirm that the above information given by us is to be true and we voluntarily executed this document&lt;br /&gt;We hereby agree to indemnify and keep indemnified CHINESE CEMETERY ASSOCIATION OF KEPONG, JINJANG &amp;amp; BATU VILLAGE (herein aftered reffered to as the &quot;Committee&quot; against all expenses, loses liability. (whether criminal or civil) damages and costs that the Committee may suffer, sustain or incur as a result, whether directly or indirectly of any brea [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 數額 Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 數額&lt;br /&gt;Amount.
        /// </summary>
        public static string AmountBR {
            get {
                return ResourceManager.GetString("AmountBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 祖先牌位 AncestralTablet.
        /// </summary>
        public static string AncestralTablet {
            get {
                return ResourceManager.GetString("AncestralTablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 祖先牌位&lt;br /&gt;AncestralTablet.
        /// </summary>
        public static string AncestralTabletBR {
            get {
                return ResourceManager.GetString("AncestralTabletBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申請者 Applicant.
        /// </summary>
        public static string Applicant {
            get {
                return ResourceManager.GetString("Applicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申請者&lt;br /&gt;Applicant.
        /// </summary>
        public static string ApplicantBR {
            get {
                return ResourceManager.GetString("ApplicantBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全申請者 Applicants.
        /// </summary>
        public static string Applicants {
            get {
                return ResourceManager.GetString("Applicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 區 Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 區&lt;br /&gt;Area.
        /// </summary>
        public static string AreaBR {
            get {
                return ResourceManager.GetString("AreaBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorised Signature of Applicant&lt;br /&gt;申請人簽名.
        /// </summary>
        public static string AuthorisedSignatureOfApplicantBR {
            get {
                return ResourceManager.GetString("AuthorisedSignatureOfApplicantBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 砌築磚穴費&lt;br /&gt;Brick Price.
        /// </summary>
        public static string BrickPriceBR {
            get {
                return ResourceManager.GetString("BrickPriceBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 葬紙准證號碼&lt;br /&gt;Burial Certificate.
        /// </summary>
        public static string BurialCertificateBR {
            get {
                return ResourceManager.GetString("BurialCertificateBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 墓地 Cemetery.
        /// </summary>
        public static string Cemetery {
            get {
                return ResourceManager.GetString("Cemetery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 墓地申請表格&lt;br /&gt;Cemetery Application Form.
        /// </summary>
        public static string CemeteryApplicationFormBR {
            get {
                return ResourceManager.GetString("CemeteryApplicationFormBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中心&lt;br /&gt;Centre.
        /// </summary>
        public static string CentreBR {
            get {
                return ResourceManager.GetString("CentreBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 換去&lt;br /&gt;Change To.
        /// </summary>
        public static string ChangeToBR {
            get {
                return ResourceManager.GetString("ChangeToBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （中）&lt;br /&gt;Chinese Name.
        /// </summary>
        public static string ChineseNameBR {
            get {
                return ResourceManager.GetString("ChineseNameBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 骨灰殿 Columbarium.
        /// </summary>
        public static string Columbarium {
            get {
                return ResourceManager.GetString("Columbarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聯絡名&lt;br /&gt;Contact Name.
        /// </summary>
        public static string ContactNameBR {
            get {
                return ResourceManager.GetString("ContactNameBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聯絡號碼&lt;br /&gt;Contact Number.
        /// </summary>
        public static string ContactNumberBR {
            get {
                return ResourceManager.GetString("ContactNumberBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申請日期&lt;br /&gt;Create Date.
        /// </summary>
        public static string CreateDateBR {
            get {
                return ResourceManager.GetString("CreateDateBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火葬日期&lt;br /&gt;Cremate Date.
        /// </summary>
        public static string CremateDateBR {
            get {
                return ResourceManager.GetString("CremateDateBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火葬 Cremation.
        /// </summary>
        public static string Cremation {
            get {
                return ResourceManager.GetString("Cremation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火葬申請表格&lt;br /&gt;Cremation Application Form.
        /// </summary>
        public static string CremationApplicationFormBR {
            get {
                return ResourceManager.GetString("CremationApplicationFormBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生死局號碼&lt;br /&gt;Death Certificate.
        /// </summary>
        public static string DeathCertificateBR {
            get {
                return ResourceManager.GetString("DeathCertificateBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 逝世日期&lt;br /&gt;Death Date.
        /// </summary>
        public static string DeathDateBR {
            get {
                return ResourceManager.GetString("DeathDateBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 逝世登記處&lt;br /&gt;Death Registration Centre.
        /// </summary>
        public static string DeathRegistrationCentreBR {
            get {
                return ResourceManager.GetString("DeathRegistrationCentreBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 逝世者 Deceased.
        /// </summary>
        public static string Deceased {
            get {
                return ResourceManager.GetString("Deceased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 逝世者&lt;br /&gt;Deceased.
        /// </summary>
        public static string DeceasedBR {
            get {
                return ResourceManager.GetString("DeceasedBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全逝世者 Deceaseds.
        /// </summary>
        public static string Deceaseds {
            get {
                return ResourceManager.GetString("Deceaseds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除 Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除&lt;br /&gt;Delete.
        /// </summary>
        public static string DeleteBR {
            get {
                return ResourceManager.GetString("DeleteBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描述&lt;br /&gt;Description.
        /// </summary>
        public static string DescriptionBR {
            get {
                return ResourceManager.GetString("DescriptionBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 挖洞穴費&lt;br /&gt;Dig Price.
        /// </summary>
        public static string DigPriceBR {
            get {
                return ResourceManager.GetString("DigPriceBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改 Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改&lt;br /&gt;Edit.
        /// </summary>
        public static string EditBR {
            get {
                return ResourceManager.GetString("EditBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名（英）&lt;br /&gt;English Name.
        /// </summary>
        public static string EnglishNameBR {
            get {
                return ResourceManager.GetString("EnglishNameBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 風水師&lt;br /&gt;Feng Shui Master.
        /// </summary>
        public static string FengShuiMasterBR {
            get {
                return ResourceManager.GetString("FengShuiMasterBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表格 Form.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 從&lt;br /&gt;From.
        /// </summary>
        public static string FromBR {
            get {
                return ResourceManager.GetString("FromBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出葬手續交興壽板承包商&lt;br /&gt;Funeral Arrangement entrusted to the following company.
        /// </summary>
        public static string FuneralArrangementEntrustedBR {
            get {
                return ResourceManager.GetString("FuneralArrangementEntrustedBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 壽板商 Funeral Company.
        /// </summary>
        public static string FuneralCompany {
            get {
                return ResourceManager.GetString("FuneralCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 壽板商&lt;br /&gt;Funeral Company.
        /// </summary>
        public static string FuneralCompanyBR {
            get {
                return ResourceManager.GetString("FuneralCompanyBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性別&lt;br /&gt;Gender.
        /// </summary>
        public static string GenderBR {
            get {
                return ResourceManager.GetString("GenderBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有逝世者&lt;br /&gt;Has Deceased.
        /// </summary>
        public static string HasDeceasedBR {
            get {
                return ResourceManager.GetString("HasDeceasedBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住家電話&lt;br /&gt;House Phone.
        /// </summary>
        public static string HousePhoneBR {
            get {
                return ResourceManager.GetString("HousePhoneBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身份證&lt;br/&gt;NRIC No.
        /// </summary>
        public static string ICBR {
            get {
                return ResourceManager.GetString("ICBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 政府入口準字號數（如由外運棺來檳）&lt;br /&gt;Import Permit Number.
        /// </summary>
        public static string ImportPermitNumberBR {
            get {
                return ResourceManager.GetString("ImportPermitNumberBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 單 Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 單&lt;br/&gt;Invoice.
        /// </summary>
        public static string InvoiceBR {
            get {
                return ResourceManager.GetString("InvoiceBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部單 Invoices.
        /// </summary>
        public static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是定金&lt;br /&gt;Is Deposit.
        /// </summary>
        public static string IsDepositBR {
            get {
                return ResourceManager.GetString("IsDepositBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終身管理費&lt;br /&gt;LifeTimeMaintenance.
        /// </summary>
        public static string LifeTimeMaintenanceBR {
            get {
                return ResourceManager.GetString("LifeTimeMaintenanceBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聯繫 Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 樂捐維修發展基金&lt;br /&gt;Maintenance and Development Expenses.
        /// </summary>
        public static string MaintenanceDevelopmentExpensesBR {
            get {
                return ResourceManager.GetString("MaintenanceDevelopmentExpensesBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理費&lt;br /&gt;Maintenance.
        /// </summary>
        public static string MaintenanceFeesBR {
            get {
                return ResourceManager.GetString("MaintenanceFeesBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 婚姻&lt;br /&gt;Marital.
        /// </summary>
        public static string MaritalBR {
            get {
                return ResourceManager.GetString("MaritalBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雜費 Miscellaneous.
        /// </summary>
        public static string Miscellaneous {
            get {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流動電話&lt;br /&gt;Mobile Number.
        /// </summary>
        public static string MobileNumberBR {
            get {
                return ResourceManager.GetString("MobileNumberBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名&lt;br /&gt;Name.
        /// </summary>
        public static string NameBR {
            get {
                return ResourceManager.GetString("NameBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 國籍&lt;br /&gt;Nationality.
        /// </summary>
        public static string NationalityBR {
            get {
                return ResourceManager.GetString("NationalityBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新紀錄 New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新申請者 New Applicant.
        /// </summary>
        public static string NewApplicant {
            get {
                return ResourceManager.GetString("NewApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新申請者&lt;br /&gt; New Applicant.
        /// </summary>
        public static string NewApplicantBR {
            get {
                return ResourceManager.GetString("NewApplicantBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新逝世者 New Deceased.
        /// </summary>
        public static string NewDeceased {
            get {
                return ResourceManager.GetString("NewDeceased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 骨灰閣&lt;br /&gt;Niche.
        /// </summary>
        public static string NicheBR {
            get {
                return ResourceManager.GetString("NicheBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全骨灰閣&lt;br /&gt;Niches.
        /// </summary>
        public static string NichesBR {
            get {
                return ResourceManager.GetString("NichesBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編號&lt;br /&gt;No..
        /// </summary>
        public static string No_BR {
            get {
                return ResourceManager.GetString("No_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 沒記錄 No record.
        /// </summary>
        public static string NoRecord {
            get {
                return ResourceManager.GetString("NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已付&lt;br /&gt;Paid.
        /// </summary>
        public static string PaidBR {
            get {
                return ResourceManager.GetString("PaidBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付費方式&lt;br /&gt;Payment Method.
        /// </summary>
        public static string PaymentMethodBR {
            get {
                return ResourceManager.GetString("PaymentMethodBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付費備註&lt;br /&gt;Payment Remark.
        /// </summary>
        public static string PaymentRemarkBR {
            get {
                return ResourceManager.GetString("PaymentRemarkBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 墓地 Plot.
        /// </summary>
        public static string Plot {
            get {
                return ResourceManager.GetString("Plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 墓地&lt;br /&gt;Plot.
        /// </summary>
        public static string PlotBR {
            get {
                return ResourceManager.GetString("PlotBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 墓地費用&lt;br /&gt;Plot Price.
        /// </summary>
        public static string PlotPriceBR {
            get {
                return ResourceManager.GetString("PlotPriceBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 墓地種類 Plot Type.
        /// </summary>
        public static string PlotType {
            get {
                return ResourceManager.GetString("PlotType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 墓地種類&lt;br /&gt;Plot Type.
        /// </summary>
        public static string PlotTypeBR {
            get {
                return ResourceManager.GetString("PlotTypeBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 價格&lt;br /&gt;Price.
        /// </summary>
        public static string PriceBR {
            get {
                return ResourceManager.GetString("PriceBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收據 Receipt.
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收據&lt;br /&gt;Receipt.
        /// </summary>
        public static string ReceiptBR {
            get {
                return ResourceManager.GetString("ReceiptBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已有收據&lt;br /&gt;Receipt Issued.
        /// </summary>
        public static string ReceiptIssuedBR {
            get {
                return ResourceManager.GetString("ReceiptIssuedBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部收據 Receipts.
        /// </summary>
        public static string Receipts {
            get {
                return ResourceManager.GetString("Receipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申請人與逝世者關係&lt;br /&gt;Relationship.
        /// </summary>
        public static string RelationshipBR {
            get {
                return ResourceManager.GetString("RelationshipBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信仰&lt;br /&gt;Religion.
        /// </summary>
        public static string ReligionBR {
            get {
                return ResourceManager.GetString("ReligionBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剩餘數額 Remaining Amount.
        /// </summary>
        public static string RemainingAmount {
            get {
                return ResourceManager.GetString("RemainingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剩餘數額&lt;br /&gt;Remaining Amount.
        /// </summary>
        public static string RemainingAmountBR {
            get {
                return ResourceManager.GetString("RemainingAmountBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 備註&lt;br /&gt;Remark.
        /// </summary>
        public static string RemarkBR {
            get {
                return ResourceManager.GetString("RemarkBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除 Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入 Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存 Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索 Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已移位至&lt;br /&gt;Shifted To.
        /// </summary>
        public static string ShiftedToBR {
            get {
                return ResourceManager.GetString("ShiftedToBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移位至&lt;br /&gt;Shift To.
        /// </summary>
        public static string ShiftToBR {
            get {
                return ResourceManager.GetString("ShiftToBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地點&lt;br /&gt;Site.
        /// </summary>
        public static string SiteBR {
            get {
                return ResourceManager.GetString("SiteBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尺寸&lt;br /&gt;Size.
        /// </summary>
        public static string SizeBR {
            get {
                return ResourceManager.GetString("SizeBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空間 Space.
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輸入1&lt;br /&gt;Text1.
        /// </summary>
        public static string Text1BR {
            get {
                return ResourceManager.GetString("Text1BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輸入2&lt;br /&gt;Text2.
        /// </summary>
        public static string Text2BR {
            get {
                return ResourceManager.GetString("Text2BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輸入3&lt;br /&gt;Text3.
        /// </summary>
        public static string Text3BR {
            get {
                return ResourceManager.GetString("Text3BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 至&lt;br /&gt;To.
        /// </summary>
        public static string ToBR {
            get {
                return ResourceManager.GetString("ToBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 轉讓至&lt;br /&gt;Transfer To.
        /// </summary>
        public static string TransferToBR {
            get {
                return ResourceManager.GetString("TransferToBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管草基金&lt;br /&gt;Turf Maintenance Fees.
        /// </summary>
        public static string TurfMaintenanceFeesBR {
            get {
                return ResourceManager.GetString("TurfMaintenanceFeesBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 種類&lt;br /&gt;Type.
        /// </summary>
        public static string TypeBR {
            get {
                return ResourceManager.GetString("TypeBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除聯繫 Unlink.
        /// </summary>
        public static string Unlink {
            get {
                return ResourceManager.GetString("Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 骨灰甕&lt;br /&gt;Urn.
        /// </summary>
        public static string UrnBR {
            get {
                return ResourceManager.GetString("UrnBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 後牆及行人道費&lt;br /&gt;Wall Price.
        /// </summary>
        public static string WallPriceBR {
            get {
                return ResourceManager.GetString("WallPriceBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
    }
}
